### PR TITLE
Fix atob error, add url params

### LINKED ISSUE #1005: Can't pass credentials from URL
Seems like code merged in #644 no longer works, as now `window.location.hash` seems to be prepended with `#!/`. This should be really easily fixable by changing `window.location.hash.substring(1)` to `window.location.hash.substring(3)`.

### PR DESCRIPTION
**Pull request by AStove**
fixes #1005
This started out as just the issue fix but found it a weird way to do it so I tried to improve it. It now also no longer gives the atob error in the console.

- Remove /#! from the url this is foreign for most web stuff and confusing. Old URLs should keep working by redirecting to the /.
- Add url parameters
- Add documentation for the url paramters.

### CODE REVIEW

**Comment by lorenzhs** [comment]
Hm, https://latest.glowing-bear.org/pull/1096/?host=example.com doesn't work for me, neither in Firefox nor in Chrome. Both redirect to https://latest.glowing-bear.org/pull/1096/?host=example.com#!/ (with the trailing `#!`. Any idea why?

**Comment by AStove** [comment]
Ah, yes. Because in the HTML I've added `<base href="/">` This now takes the javascript files from / and not from /pull/1096. (I did not know this existed.) So you are testing with all the .js files from the lastest build and not from the PR. I'll try to play around with it some more to see if this `<base>` tag is strictly nescessary.

**Comment by lorenzhs** [comment]
Ugh. That's a breaking change (not just for latest, people might have deployed GB at any location they like), we can't do that, and definitely not for a feature that only a handful of people use

**Comment by AStove** [comment]
Not if we can set the base dynamically on runtime.

**Comment by AStove** [comment]
Ok so, sorry for the commit spam. I had some problems with clearing the cache because it kept redirecting.

- Removed a part where the hash would be used to autoconnect. I don't know what the purpose of that was since the autoconnect is already saved in storage.
- No more base
- Old links with #! should still work like before

Some links for testing, be sure to clear the cache like always:

- https://latest.glowing-bear.org/pull/1096/?host=example.com
- https://latest.glowing-bear.org/pull/1096/?host=example.com&port=666
- https://latest.glowing-bear.org/pull/1096/?host=example.com&port=666&autoconnect=true
- https://latest.glowing-bear.org/pull/1096/?path=testpath

**Comment by lorenzhs** [comment]
Aaah uh sorry I didn't notice this before, but you're currently using GET parameters. These are included in the request to the server, meaning using it this way would send all connection details included in the URL to the server, which is an absolute no-go. Using the URL hash avoids this because the hash is never sent to the server.

**Comment by AStove** [comment]
This time with hash parameters instead of get parameters

https://latest.glowing-bear.org/pull/1096/#host=example.com
https://latest.glowing-bear.org/pull/1096/#host=example.com&port=666
https://latest.glowing-bear.org/pull/1096/#host=example.com&port=666&autoconnect=true
https://latest.glowing-bear.org/pull/1096/#path=testpath
https://latest.glowing-bear.org/pull/1096/#!/ (does nothing, just to check if old bookmarks would break

File: js/glowingbear.js [hunk 1]
```diff
@@ -687,7 +687,26 @@ weechat.controller('WeechatCtrl', ['$rootScope', '$scope', '$store', '$timeout',
         }
     };
 
+    
+    $scope.parseHash = function() {
+
+        //Fill in url parameters, they take precedence over the stored settings, but store them
+        var params = $location.$$hash.split('&').map(function(val) { return {key: val.split('=')[0], value: val.split('=')[1]}; });
```
Comment (lorenzhs) [inline js/glowingbear.js]: according to the linter there's a semicolon missing on this line in column 126 but tbh it's so dense I can't really parse it

File: js/glowingbear.js [hunk 2]
```diff
@@ -687,7 +687,26 @@ weechat.controller('WeechatCtrl', ['$rootScope', '$scope', '$store', '$timeout',
...
+        var hostParam = params.find(function(p) { return p.key === 'host'; });
+        var portParam = params.find(function(p) { return p.key === 'port'; });
+        var pathParam = params.find(function(p) { return p.key === 'path'; });
+        var passwordParam = params.find(function(p) { return p.key === 'password'; });
+        var autoconnectParam = params.find(function(p) { return p.key === 'autoconnect'; });
+        if(hostParam) { $scope.settings.host = hostParam.value; $scope.settings.hostField = hostParam.value;}
+        if(portParam) { $scope.settings.port =  parseInt(portParam.value);}
+        if(pathParam) { $scope.settings.path = pathParam.value;}
```
Comment (lorenzhs) [inline js/glowingbear.js]: If `pathParam` is set, I think `settings.hostField` should be set to `host + ':' + port + '/' + path` so that the changed path is visible in the UI

File: js/glowingbear.js (hunk 1 above)
Comment (lorenzhs) [reply js/glowingbear.js]: In JS, mappers can have side effects, so you can do
```js
var params;
$location.$$hash.split('&').map(function(val) {
    var segs = val.split('=');
    params[segs[0]] = segs[1];
});
```
and then you can simply use `params['host']` etc

File: js/glowingbear.js [hunk 3]
```diff
@@ -687,7 +687,26 @@ weechat.controller('WeechatCtrl', ['$rootScope', '$scope', '$store', '$timeout',
...
+        if(passwordParam) { $scope.settings.password = passwordParam.value;}
```
Comment (lorenzhs) [inline js/glowingbear.js]: The model for the password field is not `settings.password`, it's a password field in the scope which is saved to settings if the checkbox is set. I don't think it should just be saved to the settings if set in the hash.

Comment (AStove) [reply js/glowingbear.js]: Oh ok, this is not intentional, copy pase error.

File: js/glowingbear.js (hunk 1 above)
Comment (AStove) [reply js/glowingbear.js]: I initially went for a find() with a lambda but this is not ES6.

Comment (AStove) [reply js/glowingbear.js]: Or even dot notation params.host, the linter suggested.

**Comment by lorenzhs** [comment]
Thanks a lot! Rebased and merged.
